# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protocols_pb2 as protocols__pb2


class RsyncServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RsyncMethod = channel.unary_unary(
        '/example.RsyncService/RsyncMethod',
        request_serializer=protocols__pb2.ClientRequest.SerializeToString,
        response_deserializer=protocols__pb2.ServerResponse.FromString,
        )


class RsyncServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RsyncMethod(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RsyncServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RsyncMethod': grpc.unary_unary_rpc_method_handler(
          servicer.RsyncMethod,
          request_deserializer=protocols__pb2.ClientRequest.FromString,
          response_serializer=protocols__pb2.ServerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'example.RsyncService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
