# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocols.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocols.proto',
  package='example',
  syntax='proto3',
  serialized_pb=_b('\n\x0fprotocols.proto\x12\x07\x65xample\"9\n\rClientRequest\x12\x15\n\rdirectoryName\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\"1\n\nClientHash\x12\x11\n\tfileNames\x18\x01 \x01(\t\x12\x10\n\x08\x66ileHash\x18\x02 \x01(\x05\"A\n\x0eServerResponse\x12\x1c\n\x05\x66iles\x18\x01 \x03(\x0b\x32\r.example.File\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\"B\n\x04\x46ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x13\n\x0bisDirectory\x18\x02 \x01(\x08\x12\x13\n\x0b\x66ileContent\x18\x03 \x01(\x0c\x32P\n\x0cRsyncService\x12@\n\x0bRsyncMethod\x12\x16.example.ClientRequest\x1a\x17.example.ServerResponse\"\x00\x62\x06proto3')
)




_CLIENTREQUEST = _descriptor.Descriptor(
  name='ClientRequest',
  full_name='example.ClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='directoryName', full_name='example.ClientRequest.directoryName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='example.ClientRequest.timestamp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=85,
)


_CLIENTHASH = _descriptor.Descriptor(
  name='ClientHash',
  full_name='example.ClientHash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileNames', full_name='example.ClientHash.fileNames', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fileHash', full_name='example.ClientHash.fileHash', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=136,
)


_SERVERRESPONSE = _descriptor.Descriptor(
  name='ServerResponse',
  full_name='example.ServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='files', full_name='example.ServerResponse.files', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='example.ServerResponse.timestamp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=203,
)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='example.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='example.File.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isDirectory', full_name='example.File.isDirectory', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fileContent', full_name='example.File.fileContent', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=271,
)

_SERVERRESPONSE.fields_by_name['files'].message_type = _FILE
DESCRIPTOR.message_types_by_name['ClientRequest'] = _CLIENTREQUEST
DESCRIPTOR.message_types_by_name['ClientHash'] = _CLIENTHASH
DESCRIPTOR.message_types_by_name['ServerResponse'] = _SERVERRESPONSE
DESCRIPTOR.message_types_by_name['File'] = _FILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientRequest = _reflection.GeneratedProtocolMessageType('ClientRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTREQUEST,
  __module__ = 'protocols_pb2'
  # @@protoc_insertion_point(class_scope:example.ClientRequest)
  ))
_sym_db.RegisterMessage(ClientRequest)

ClientHash = _reflection.GeneratedProtocolMessageType('ClientHash', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTHASH,
  __module__ = 'protocols_pb2'
  # @@protoc_insertion_point(class_scope:example.ClientHash)
  ))
_sym_db.RegisterMessage(ClientHash)

ServerResponse = _reflection.GeneratedProtocolMessageType('ServerResponse', (_message.Message,), dict(
  DESCRIPTOR = _SERVERRESPONSE,
  __module__ = 'protocols_pb2'
  # @@protoc_insertion_point(class_scope:example.ServerResponse)
  ))
_sym_db.RegisterMessage(ServerResponse)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'protocols_pb2'
  # @@protoc_insertion_point(class_scope:example.File)
  ))
_sym_db.RegisterMessage(File)



_RSYNCSERVICE = _descriptor.ServiceDescriptor(
  name='RsyncService',
  full_name='example.RsyncService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=273,
  serialized_end=353,
  methods=[
  _descriptor.MethodDescriptor(
    name='RsyncMethod',
    full_name='example.RsyncService.RsyncMethod',
    index=0,
    containing_service=None,
    input_type=_CLIENTREQUEST,
    output_type=_SERVERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RSYNCSERVICE)

DESCRIPTOR.services_by_name['RsyncService'] = _RSYNCSERVICE

# @@protoc_insertion_point(module_scope)
